### PR TITLE
Add new BAAAHS shader, mockup BeatInfo utilities for shadertoy

### PR DESCRIPTION
**Pull request by bencbartlett**
[capture (1).webm](https://github.com/baaahs/sparklemotion/assets/6800253/109ced0a-6981-4f2d-a849-28026acca730)

### CODE REVIEW

**Comment by bencbartlett** [comment]
Also refined the sheep logo drawing utilities to be easier to use and added some stylistic components like lens flares:

[capture (2).webm](https://github.com/baaahs/sparklemotion/assets/6800253/ca0c90b1-380e-4ed0-af1c-f3751f574125)

**Comment by bencbartlett** [comment]
with horizontal option: 
[capture (3).webm](https://github.com/baaahs/sparklemotion/assets/6800253/8590e286-fae0-42b9-97a9-6215c8269485)

**Comment by xian** [comment]
gaahhhhhhuhhhhh 🤤 <3

**Comment by xian** [comment]
:meltyface:

**Comment by bencbartlett** [comment]
Me reviewing and approving my own pull requests be like 

image

**Pull request merged**
